apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    prometheus: server
    role: alert-rules
  name: k8s-tls-watcher-alerts
spec:
  groups:
  - name: tls-secrets
    rules:
    - alert: CertsNearingExpiry
      annotations:
        message: SSL Certificate is about to expiry
      expr: tls_certs_expiry_in_days < 14
      for: 30m
      labels:
        severity: warning
    - alert: CertsExpired
      annotations:
        message: SSL Certificate expired
      expr: tls_certs_expiry_in_days < 0
      for: 30m
      labels:
        severity: critical