---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: k8s-tls-watcher
rules:
  - apiGroups: [""]
    resources:
      - "secrets"
    verbs:
      - "get"
      - "list"
---

apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: k8s-tls-watcher
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: k8s-tls-watcher
subjects:
  - name: k8s-tls-watcher
    namespace: default
    kind: ServiceAccount